@echo off
echo Installing dependencies...
npm install @supabase/supabase-js @tensorflow/tfjs tailwindcss postcss autoprefixer
echo Creating .env.local...
echo NEXT_PUBLIC_SUPABASE_URL=https://cdsdnueugkfbzbdgsyvi.supabase.co > .env.local
echo NEXT_PUBLIC_SUPABASE_ANON_KEY=sb_publishable_8j3AUxlAPoKz9tmB0EKC1g_g_0wtSDp >> .env.local
echo SUPABASE_SERVICE_ROLE_KEY=sb_secret_M2hVj0-_nFo-e8x3Ksu1pQ_dUfcsP8i >> .env.local
echo Setting up Tailwind...
npx tailwindcss init -p
echo Starting app...
npm run dev