// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/dist/lib/metadata/types/metadata-interface.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin/page.tsx
{
  const handler = {} as typeof import("../../src/app/admin/page.js")
  handler satisfies AppPageConfig<"/admin">
}

// Validate ../../src/app/age/page.tsx
{
  const handler = {} as typeof import("../../src/app/age/page.js")
  handler satisfies AppPageConfig<"/age">
}

// Validate ../../src/app/albums/[albumId]/page.tsx
{
  const handler = {} as typeof import("../../src/app/albums/[albumId]/page.js")
  handler satisfies AppPageConfig<"/albums/[albumId]">
}

// Validate ../../src/app/albums/page.tsx
{
  const handler = {} as typeof import("../../src/app/albums/page.js")
  handler satisfies AppPageConfig<"/albums">
}

// Validate ../../src/app/chat/page.tsx
{
  const handler = {} as typeof import("../../src/app/chat/page.js")
  handler satisfies AppPageConfig<"/chat">
}

// Validate ../../src/app/contact/page.tsx
{
  const handler = {} as typeof import("../../src/app/contact/page.js")
  handler satisfies AppPageConfig<"/contact">
}

// Validate ../../src/app/education/page.tsx
{
  const handler = {} as typeof import("../../src/app/education/page.js")
  handler satisfies AppPageConfig<"/education">
}

// Validate ../../src/app/forums/page.tsx
{
  const handler = {} as typeof import("../../src/app/forums/page.js")
  handler satisfies AppPageConfig<"/forums">
}

// Validate ../../src/app/login/page.tsx
{
  const handler = {} as typeof import("../../src/app/login/page.js")
  handler satisfies AppPageConfig<"/login">
}

// Validate ../../src/app/page.tsx
{
  const handler = {} as typeof import("../../src/app/page.js")
  handler satisfies AppPageConfig<"/">
}

// Validate ../../src/app/privacy/page.tsx
{
  const handler = {} as typeof import("../../src/app/privacy/page.js")
  handler satisfies AppPageConfig<"/privacy">
}

// Validate ../../src/app/profile/page.tsx
{
  const handler = {} as typeof import("../../src/app/profile/page.js")
  handler satisfies AppPageConfig<"/profile">
}

// Validate ../../src/app/safety/page.tsx
{
  const handler = {} as typeof import("../../src/app/safety/page.js")
  handler satisfies AppPageConfig<"/safety">
}

// Validate ../../src/app/schedule/page.tsx
{
  const handler = {} as typeof import("../../src/app/schedule/page.js")
  handler satisfies AppPageConfig<"/schedule">
}

// Validate ../../src/app/signup/page.tsx
{
  const handler = {} as typeof import("../../src/app/signup/page.js")
  handler satisfies AppPageConfig<"/signup">
}

// Validate ../../src/app/terms/page.tsx
{
  const handler = {} as typeof import("../../src/app/terms/page.js")
  handler satisfies AppPageConfig<"/terms">
}

// Validate ../../src/app/wall/page.tsx
{
  const handler = {} as typeof import("../../src/app/wall/page.js")
  handler satisfies AppPageConfig<"/wall">
}

// Validate ../../src/app/admin/embeddings/backfill/route.ts
{
  const handler = {} as typeof import("../../src/app/admin/embeddings/backfill/route.js")
  handler satisfies RouteHandlerConfig<"/admin/embeddings/backfill">
}

// Validate ../../src/app/api/admin/album-access/route.ts
{
  const handler = {} as typeof import("../../src/app/api/admin/album-access/route.js")
  handler satisfies RouteHandlerConfig<"/api/admin/album-access">
}

// Validate ../../src/app/api/admin/hide/route.ts
{
  const handler = {} as typeof import("../../src/app/api/admin/hide/route.js")
  handler satisfies RouteHandlerConfig<"/api/admin/hide">
}

// Validate ../../src/app/api/admin/reports/route.ts
{
  const handler = {} as typeof import("../../src/app/api/admin/reports/route.js")
  handler satisfies RouteHandlerConfig<"/api/admin/reports">
}

// Validate ../../src/app/api/age/accept/route.ts
{
  const handler = {} as typeof import("../../src/app/api/age/accept/route.js")
  handler satisfies RouteHandlerConfig<"/api/age/accept">
}

// Validate ../../src/app/api/ai/aesthetic/route.ts
{
  const handler = {} as typeof import("../../src/app/api/ai/aesthetic/route.js")
  handler satisfies RouteHandlerConfig<"/api/ai/aesthetic">
}

// Validate ../../src/app/api/albums/[albumId]/access/route.ts
{
  const handler = {} as typeof import("../../src/app/api/albums/[albumId]/access/route.js")
  handler satisfies RouteHandlerConfig<"/api/albums/[albumId]/access">
}

// Validate ../../src/app/api/albums/[albumId]/photos/route.ts
{
  const handler = {} as typeof import("../../src/app/api/albums/[albumId]/photos/route.js")
  handler satisfies RouteHandlerConfig<"/api/albums/[albumId]/photos">
}

// Validate ../../src/app/api/albums/route.ts
{
  const handler = {} as typeof import("../../src/app/api/albums/route.js")
  handler satisfies RouteHandlerConfig<"/api/albums">
}

// Validate ../../src/app/api/blocks/route.ts
{
  const handler = {} as typeof import("../../src/app/api/blocks/route.js")
  handler satisfies RouteHandlerConfig<"/api/blocks">
}

// Validate ../../src/app/api/embeddings/rebuild/route.ts
{
  const handler = {} as typeof import("../../src/app/api/embeddings/rebuild/route.js")
  handler satisfies RouteHandlerConfig<"/api/embeddings/rebuild">
}

// Validate ../../src/app/api/embeddings/upsert/route.ts
{
  const handler = {} as typeof import("../../src/app/api/embeddings/upsert/route.js")
  handler satisfies RouteHandlerConfig<"/api/embeddings/upsert">
}

// Validate ../../src/app/api/match/recommendations/advanced/route.ts
{
  const handler = {} as typeof import("../../src/app/api/match/recommendations/advanced/route.js")
  handler satisfies RouteHandlerConfig<"/api/match/recommendations/advanced">
}

// Validate ../../src/app/api/match/recommendations/blended/route.ts
{
  const handler = {} as typeof import("../../src/app/api/match/recommendations/blended/route.js")
  handler satisfies RouteHandlerConfig<"/api/match/recommendations/blended">
}

// Validate ../../src/app/api/match/recommendations/route.ts
{
  const handler = {} as typeof import("../../src/app/api/match/recommendations/route.js")
  handler satisfies RouteHandlerConfig<"/api/match/recommendations">
}

// Validate ../../src/app/api/posts/route.ts
{
  const handler = {} as typeof import("../../src/app/api/posts/route.js")
  handler satisfies RouteHandlerConfig<"/api/posts">
}

// Validate ../../src/app/api/profile/preferences/route.ts
{
  const handler = {} as typeof import("../../src/app/api/profile/preferences/route.js")
  handler satisfies RouteHandlerConfig<"/api/profile/preferences">
}

// Validate ../../src/app/api/profile/upsert/route.ts
{
  const handler = {} as typeof import("../../src/app/api/profile/upsert/route.js")
  handler satisfies RouteHandlerConfig<"/api/profile/upsert">
}

// Validate ../../src/app/api/reports/route.ts
{
  const handler = {} as typeof import("../../src/app/api/reports/route.js")
  handler satisfies RouteHandlerConfig<"/api/reports">
}

// Validate ../../src/app/api/send-email/route.ts
{
  const handler = {} as typeof import("../../src/app/api/send-email/route.js")
  handler satisfies RouteHandlerConfig<"/api/send-email">
}

// Validate ../../src/app/api/signup/route.ts
{
  const handler = {} as typeof import("../../src/app/api/signup/route.js")
  handler satisfies RouteHandlerConfig<"/api/signup">
}

// Validate ../../src/app/api/upload/route.ts
{
  const handler = {} as typeof import("../../src/app/api/upload/route.js")
  handler satisfies RouteHandlerConfig<"/api/upload">
}

// Validate ../../src/app/api/uploads/sign/route.ts
{
  const handler = {} as typeof import("../../src/app/api/uploads/sign/route.js")
  handler satisfies RouteHandlerConfig<"/api/uploads/sign">
}





// Validate ../../src/app/layout.tsx
{
  const handler = {} as typeof import("../../src/app/layout.js")
  handler satisfies LayoutConfig<"/">
}
